#!/usr/bin/env bash

e_arrow 'Some post-installation magic'


#!/usr/bin/env bash

mkdir -p /home/renato/Programs


## SUBLIME TEXT 
if [ -d "$HOME/Programs/Sublime\ Text\ 2/" ]; then
  e_success 'Sublime text is already installed'
else
  e_arrow 'Installing sublime_text'
  wget http://c758482.r82.cf2.rackcdn.com/Sublime%20Text%202.0.2%20x64.tar.bz2 -P /home/renato/Programs
  tar xvjf /home/renato/Programs/Sublime\ Text\ 2.0.2\ x64.tar.bz2 -C /home/renato/Programs
  sudo ln -s /home/renato/Programs/Sublime\ Text\ 2/sublime_text /usr/bin/sublime
  e_success 'Done!'
fi


#===========================================================
# 1.                     ZSH
#===========================================================
if [[ $SHELL =~ zsh ]]; then
  e_success 'You already use zsh. Awesome!'
else
  e_arrow 'Changing shell to zsh'
  sudo chsh -s $(which zsh)
fi

#===========================================================
# 3.                     OH-MY-ZSH
#===========================================================
if [ -d "$HOME/.oh-my-zsh" ]; then
  e_already 'oh-my-zsh'
else
  e_arrow 'Installing oh-my-zsh'
  curl -Ls https://github.com/robbyrussell/oh-my-zsh/raw/master/tools/install.sh | sh > /dev/null 2>&1
fi

#===========================================================
# 4.                     PYTHON SHIT
#===========================================================
e_arrow 'Installing pip'
sudo apt-get -qq install python-pip
sudo pip install virtualenv virtualenvwrapper


#===========================================================
# 5.                     FONTS
#===========================================================
e_arrow 'Installing fonts'
sudo mkdir /usr/share/fonts/truetype/custom -p > /dev/null 2>&1
sudo cp resources/fonts/Monaco_Linux-Powerline.ttf /usr/share/fonts/truetype/custom/
e_arrow 'Rebuilding fonts cache'
sudo fc-cache -f
  